name 'instana-agent'
maintainer 'INSTANA Inc'
maintainer_email 'stefan.staudenmeyer@instana.com'
license 'Proprietary - All Rights Reserved'
description 'Installs/Configures instana-agent'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.0'
provides 'instana-agent::default'
provides 'instana-agent::check_java'
provides 'instana-agent::download'
provides 'instana-agent::install'
provides 'instana-agent::run'
recipe 'default', 'Check the java installation, download and start the agent'
recipe 'check_java', 'Check the java installation, JDK and Version'
recipe 'download', 'Download the instana agent'
recipe 'install', 'Unzips the instana agent to a specified location'
recipe 'run', 'Runs the instana agent'
