name 'instana-agent-onprem'
maintainer '2016 Instana, Inc.'
maintainer_email 'stefan.staudenmeyer@instana.com'
license 'All rights reserved'
description 'Installs/Configures instana-agent-onprem'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.0'
depends 'java_se', '~> 8.92.0'
provides 'instana-agent-onprem::default'
provides 'instana-agent-onprem::check_java'
provides 'instana-agent-onprem::download'
provides 'instana-agent-onprem::install'
provides 'instana-agent-onprem::run'
recipe 'default', 'Check the java installation, download and start the agent'
recipe 'check_java', 'Check the java installation, JDK and Version'
recipe 'download', 'Download the instana agent'
recipe 'install', 'Unzips the instana agent to a specified location'
recipe 'run', 'Runs the instana agent'
